dataset: openai/gsm8k
subset: main
split: train[:5]
seed: 123
output_dir: Outputs/gsm8k

dataset: simpleqa
split: test # Keep as placeholder for uniformity
n_samples: 300
seed: 123
output_dir: Outputs/simpleqa